services:
  legal-diff-demo:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # 開発時のホットリロード用（本番環境では不要）
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  # 開発用サービス（開発時に使用）
  legal-diff-demo-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev